---
title: "Project 3 - GLMM"
authors: "Silvy van Kuijk and Tony Di Fiore"
date: "4/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

This R Markdown document contains the R script that 

```{r}
setwd('C:/Users/Silvy/Documents/R/Repos/Project3WeatherPatterns')
library(dplyr)
library(lubridate)
library(stringr)
library(lme4)
library(tidyverse)

```

## Transforming dataset into separate Titi and Howler datasets

```{r}
HowlersInDay <- data %>% filter(Howlers == TRUE) %>% group_by(Date) %>% summarize(howlerCount = sum(Howlers), totalCallTime = sum(CallDurationInSec, na.rm = TRUE))

TitisInDay <- data %>% filter(Titis == TRUE) %>% group_by(Date) %>% summarise(titiCount = sum(Titis), totalCallTime = sum(CallDurationInSec, na.rm = TRUE))

```

```{r}
data_per_day <- data.frame(unique(data$Date))
colnames(data_per_day) <- "Date"

Lunar_Data <- read.csv(file = 'Johnblake_dates_with_phase.csv')
Dates_Plus_Lunar <- left_join(data_per_day, Lunar_Data, by = "Date")

Overnight_Temperatures <- read.csv('overnight_temperatures.csv')
colnames(Overnight_Temperatures)[colnames(Overnight_Temperatures) == 'today'] <- 'Date'
Overnight_Temperatures <- Overnight_Temperatures %>% 
  select(Date, today_average, lastnight_average, lastnight_min) 
Dates_Lunar_Overnight <- left_join(Dates_Plus_Lunar, Overnight_Temperatures, by = "Date")

Dates_Lunar_Overnight$Year <- format(as.Date(Dates_Lunar_Overnight$Date, format="%m/%d/%Y"),"%Y")

Dates_Lunar_Overnight <- semi_join(Dates_Lunar_Overnight, data[ , c("Titis")], by = "Date", copy = TRUE)
write.csv(Dates_Lunar_Overnight, "ForMayFourteen.csv",na="NA",row.names=TRUE)

```

## GLMM

```{r}
GLMM_Data <- read.csv("ForMayFourteen.csv")


Model1 <- glm(data = GLMM_Data, family=binomial, formula = Titis ~ Rain + today_average + lastnight_average + lastnight_min)
summary(Model1)
AIC(Model1)
```
